"""empty message

Revision ID: 40341817e4f8
Revises: b43586199f3e
Create Date: 2017-08-26 17:25:17.730577

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision = '40341817e4f8'
down_revision = 'b43586199f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_token', table_name='token')
    op.drop_column('token', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_token_token', 'token', ['token'], unique=True)
    # ### end Alembic commands ###
