"""empty message

Revision ID: 657859e17f4d
Revises: 24e3cbc37a42
Create Date: 2017-08-25 18:29:52.865777

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '657859e17f4d'
down_revision = '24e3cbc37a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sqlalchemy_utils.types.password.PasswordType(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('admin', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('identity', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_identity'), 'token', ['identity'], unique=False)
    op.create_index(op.f('ix_token_token'), 'token', ['token'], unique=True)
    op.create_table('link',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_index(op.f('ix_token_token'), table_name='token')
    op.drop_index(op.f('ix_token_identity'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
