"""empty message

Revision ID: 6d8674858174
Revises: f5ff7ddfa258
Create Date: 2017-08-26 17:46:04.360926

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision = '6d8674858174'
down_revision = 'f5ff7ddfa258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('link_token_id_fkey', 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'token', ['token_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key('link_token_id_fkey', 'link', 'token', ['token_id'], ['id'])
    # ### end Alembic commands ###
