"""empty message

Revision ID: af5307a8e08d
Revises: d9f8ccab13a2
Create Date: 2017-08-27 23:45:02.151099

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision = 'af5307a8e08d'
down_revision = 'd9f8ccab13a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed_link',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('removed_token',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('removed_token')
    op.drop_table('removed_link')
    # ### end Alembic commands ###
