"""empty message

Revision ID: d9f8ccab13a2
Revises: 6d8674858174
Create Date: 2017-08-26 22:06:18.963505

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision = 'd9f8ccab13a2'
down_revision = '6d8674858174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('active', sa.Boolean(), server_default=sa.text('FALSE'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'active')
    # ### end Alembic commands ###
