"""empty message

Revision ID: f5ff7ddfa258
Revises: 40341817e4f8
Create Date: 2017-08-26 17:42:53.973759

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy import Text


# revision identifiers, used by Alembic.
revision = 'f5ff7ddfa258'
down_revision = '40341817e4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('link_token_id_fk', 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'token', ['token_id'], ['id'])
    op.drop_constraint('token_user_id_fkey', 'token', type_='foreignkey')
    op.create_foreign_key(None, 'token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token', type_='foreignkey')
    op.create_foreign_key('token_user_id_fkey', 'token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key('link_token_id_fk', 'link', 'token', ['token_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
